[workspace]
members = [
  "os/kernel",
  "os/crates/*",
  # "os/arch",
  "os/userspace/init",
  "os/qapi",
]
resolver = "2"

[workspace.dependencies]
arch = { path = "os/arch" }
serial = { path = "os/crates/serial" }
sync = { path = "os/crates/sync" }
entry = { path = "os/crates/entry" }
loader = { path = "os/crates/loader" }
trie = { path = "os/crates/trie" }
qapi = { path = "os/qapi" }

zerocopy = { version = "0.8.26", features = ["derive"] }
uart_16550 = "0.3.0"
log = "0.4.22"
derive_more = { version = "2.0.1", default-features = false, features = [
  "display",
  "error",
  "from",
  "debug",
  "deref",
  "deref_mut",
  "into",
  "try_from",
] }
sealed = "0.6.0"
tap = "1.0.1"

[profile.dev]
debug = "full"
opt-level = 1

[profile.release]
debug = "full"
incremental = true

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"
