[workspace]
members = [
  "os/kernel",
  "os/crates/*",
  "os/userspace/init",
  "os/userspace/ulib",
  "os/qapi",
  "os/qapi-macros",
]
resolver = "2"

[workspace.dependencies]
serial = { path = "os/crates/serial" }
sync = { path = "os/crates/sync" }
entry = { path = "os/crates/entry" }
loader = { path = "os/crates/loader" }
selfie = { path = "os/crates/selfie" }
qapi = { path = "os/qapi" }
ulib = { path = "os/userspace/ulib" }

hashbrown = "0.15.5"
zerocopy = { version = "0.8.26", features = ["derive"] }
uart_16550 = "0.3.0"
log = "0.4.22"
derive_more = { version = "2.0.1", default-features = false, features = [
  "display",
  "error",
  "from",
  "debug",
  "deref",
  "deref_mut",
  "into",
  "try_from",
] }
sealed = "0.6.0"
tap = "1.0.1"
allocator-api2 = { version = "0.2.21", default-features = false, features = [
  "alloc",
] }

[profile.dev]
debug = "full"
opt-level = 1

[profile.release]
debug = "full"
incremental = true

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"
