load("@rust//:toolchain.bzl", "rust_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "remote_python_toolchain", "system_python_wheel_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:zip_file.bzl", "zip_file_toolchain")
load("@prelude//toolchains:remote_test_execution.bzl", "remote_test_execution_toolchain")
load("@prelude//tests:test_toolchain.bzl", "noop_test_toolchain")

remote_test_execution_toolchain(
    name = "remote_test_execution",
    visibility = ["PUBLIC"],
)


noop_test_toolchain(
    name = "test",
    visibility = ["PUBLIC"],
)
python_binary(
    name = "linker",
    main = "linker.py",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    linker = "toolchains/linker.py",
    compiler = "clang",
    cxx_compiler = "clang++",
    visibility = ["PUBLIC"],
)

zip_file_toolchain(
    name = "zip_file",
    visibility = ["PUBLIC"],
)

remote_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

rust_toolchain.stable.version("1.95.0").default(
    name = "rust",
    default_edition = "2024",
    rustc_exec_triple = "x86_64-unknown-linux-gnu",
    rustc_target_triple = select({
        "prelude//os/constraints:none": "x86_64-unknown-none",
        "DEFAULT": "x86_64-unknown-linux-gnu",
    }),
    visibility = ["PUBLIC"],
)
