export_file(
    name = "linker.ld",
)

rust_binary(
    name = "kernel",
    srcs = glob(["src/**"]),
    linker_flags = [
        "-T$(location :linker.ld)",
    ],
    visibility = ["//qurios:iso-files"],
    incoming_transition = "//qurios:baremetal_transition",
    deps = [
        "//third_party/rust:limine",
    ],
)
