export_file(
    name = "linker.ld",
)

rust_library(
    name = "kernel",
    srcs = glob(["src/**"]),
    deps = [
        "//third_party/rust:limine",
        "//third_party/rust:log",
    ],
)

rust_binary(
    name = "kernel-bin",
    srcs = ["bins/kernel.rs"],
    crate_root = "bins/kernel.rs",
    linker_flags = [
        "-T$(location :linker.ld)",
    ],
    visibility = ["//qurios:iso-files"],
    incoming_transition = "//qurios:baremetal_transition",
    deps = [
        ":kernel",
    ] + select({
        "root//constraints:emulator[qemu]": ["//qurios/qurios-qemu:qurios-qemu"],
        "DEFAULT": [], 
    }),
    features = select({
        "root//constraints:emulator[qemu]": ["qemu"],
        "DEFAULT": [], 
    }),
)

rust_binary(
    name = "kernel-test",
    srcs = ["bins/kernel-test.rs"],
    crate_root = "bins/kernel-test.rs",
    linker_flags = [
        "-T$(location :linker.ld)",
    ],
    visibility = ["//qurios:iso-files"],
    incoming_transition = "//qurios:baremetal_transition",
    deps = [
        ":kernel",
        "//qurios/qurios-qemu:qurios-qemu",
    ],
)
