ENTRIES = [
    {
        'complete': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
            'rust-docs',
            'rustfmt-preview',
            'clippy-preview',
            'rust-analyzer-preview',
            'rust-src',
            'llvm-tools-preview',
            'rust-analysis',
            'miri-preview',
            'rustc-codegen-cranelift-preview',
            'rustc-dev',
        ],
        'default': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
            'rust-docs',
            'rustfmt-preview',
            'clippy-preview',
        ],
        'minimal': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
        ],
    },
    {
        'complete': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
            'rust-docs',
            'rustfmt-preview',
            'clippy-preview',
            'rust-analyzer-preview',
            'rust-src',
            'llvm-tools-preview',
            'rust-analysis',
            'miri-preview',
            'rustc-codegen-cranelift-preview',
        ],
        'default': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
            'rust-docs',
            'rustfmt-preview',
            'clippy-preview',
        ],
        'minimal': [
            'rustc',
            'cargo',
            'rust-std',
            'rust-mingw',
        ],
    },
]
