# Timeout in seconds that Limine will use before automatically booting.
timeout: 0
graphics: no
verbose: yes

# The entry name that will be displayed in the boot menu.
/QuriOS Test
    protocol: limine
    kaslr: no
    kernel_path: boot():/boot/kernel
