[package]
name = "init"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"
name = "init"
# NOTE: `staticlib` must be listed last
crate-type = ["rlib", "staticlib"]
# test = false
# bench = false

[dependencies]
allocator-api2 = { version = "0.2.21", default-features = false, features = [
  "alloc",
] }
bitvec = { version = "1.0.1", default-features = false }
derive_more.workspace = true
entry.workspace = true
hashbrown = { version = "0.15.4", features = ["allocator-api2"] }
linked_list_allocator = "0.10.5"
log.workspace = true
qapi.workspace = true
selfie.workspace = true
serial.workspace = true
spin = { version = "0.10.0", default-features = false }
sync.workspace = true
ulib.workspace = true
stack_list.workspace = true

[lints]
workspace = true
