constraint_value(
    name = "qurios",
    constraint_setting = "prelude//os/constraints:os",
    visibility = ["PUBLIC"],
)

constraint(
    name = "build_mode",
    values = [
        "debug",
        "release",
    ],
    visibility = ["PUBLIC"],
    default = "debug",
)

constraint(
    name = "emulator",
    values = [
        "none",
        "qemu",
    ],
    visibility = ["PUBLIC"],
    default = "none",
)
