config_setting(
    name = "linux_x86_64",
    constraint_values = [
        "prelude//os/constraints:linux",
        "prelude//cpu/constraints:x86_64",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "mac_arm",
    constraint_values = [
        "prelude//os/constraints:macos",
        "prelude//cpu/constraints:arm64",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "mac_x86",
    constraint_values = [
        "prelude//os/constraints:macos",
        "prelude//cpu/constraints:x86_64",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "x86_64-none",
    constraint_values = [
        "prelude//cpu/constraints:x86_64",
        "prelude//os/constraints:none",
    ],
    visibility = ["PUBLIC"],
)

config_setting(
    name = "riscv64-none",
    constraint_values = [
        "prelude//cpu/constraints:riscv64",
        "prelude//os/constraints:none",
    ],
    visibility = ["PUBLIC"],
)
