[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
test = false

[[bin]]
name = "kmain"
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
serial.workspace = true
sync.workspace = true
arch.workspace = true
derive_more.workspace = true
loader.workspace = true

limine = "0.5.0"
tap = "1.0.1"
tar-no-std = "0.3.4"
extend = "1.2.0"
heapless = "0.8.0"
qapi.workspace = true
