name: CI pipeline
on:
  pull_request:
    branches: [ v2 ]
    types: [ opened, synchronize ]
  push:
    branches: [ v2 ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup buck2
        uses: dtolnay/install-buck2@latest
      - name: Build code
        run: buck2 build //...
      - name: Test the code
        run: buck2 test //...
